#!/bin/sh

sb="#434343"

text=$(echo "$(xclip -o)" | dmenu -sb "$sb" -p "Google Translate")

[ -z $text ] && exit 1

if [ -z "$1" ]; then
    languages=$(echo -e ":ind\n:en\n:ko" | \
                dmenu -sb "$sb" -p "Select [SOURCE]:[TARGET] languages")
else
    languages=$1
fi

[ -z "$languages" ] && exit 1

notify-send "Translate" "$(trans --no-ansi "$languages" "$text")"
sleep 1.55s