#!/bin/sh

# Syncs repositories and downloads updates, meant to be run as a cronjob.

ping -q -c 1 1.1.1.1 > /dev/null || exit

notify-send "📦 Repository Sync" "Checking for package updates..."

sudo pacman -Syyuw --noconfirm || notify-send "Error downloading updates.

yay -Syua --noconfirm || notify-send "Error downloading updates.
#pkill -RTMIN+8 "${STATUSBAR:?}"

#printf "\\nUpgrade complete.\\nPress <Enter> to exit window.\\n\\n"
#read -r


Check your internet connection, if pacman is already running, or run update manually to see errors."
#pkill -RTMIN+8 "${STATUSBAR:?}"

if pacman -Qu | grep -v "\[ignored\]" then

then
	notify-send "🎁Repository Sync" "Updates available."
else
	notify-send "Repository Sync"  "Sync complete. No new packages for update."
fi