#!/bin/bash

## download mkv from youtube, ssst this is illegal actually
youtube-dl $1\
	--add-metadata --metadata-from-title "%(artist)s - %(title)s" \
	-f 'bestvideo[height<=480]+bestaudio/best[height<=480]'
	$f
notify-send "Youtube" "Check Download"
